Add .gitignore
decrypto-org/decrypto.org pull request #1
Opened 2017-08-29 14:18 UTC by cnasikas

Add .gitignore file to ignore node_modules and package-lock.json

2017-08-30 08:48 UTC, dionyziz requested changes

2017-08-30 08:48 UTC, dionyziz commented on .gitignore
> +package-lock.json
[According to documentation](https://docs.npmjs.com/files/package-lock.json), package-lock.json.json "is intended to be committed into source repositories, and therefore should not be git ignored".

2017-08-30 18:50 UTC, cnasikas commented
I made a mistake and this commits are included in pull request #2 so I am closing it.

2017-09-16 18:34 UTC, dionyziz requested changes
This PR implies that we will use npm for this project. However, the latest recommendation is yarn. In that direction, perhaps we can use a [`yarn.lock`](https://yarnpkg.com/lang/en/docs/yarn-lock/) file instead. What do you think?

2017-09-16 20:27 UTC, cnasikas commented
Of course. But we already have a yarn.lock file, right? According to docs we should commit it. We could support both npm and yarn.

2017-09-18 15:48 UTC, closed without merging